name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android64:
    runs-on: ubuntu-latest
    name: Build for Android 64-bit
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: 'latest'
          ndk: '21.4.7075529'